# Generated by Django 6.0.3 on 2026-04-04 15:18

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=api.models.code_generator, max_length=10, unique=True),
        ),
    ]
